"""creation de la table etudiant

Revision ID: 821eaa1aebd2
Revises: 
Create Date: 2025-03-10 20:48:04.747341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821eaa1aebd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etudiant',
    sa.Column('matricule', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=20), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('classe_id', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('matricule')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etudiant')
    # ### end Alembic commands ###
